### ISSUE TITLE
Where is the signal processing code for dormio

### ISSUE THREAD

**Issue by marauder37** [tomasero/openSleep#1]
Friends, you mention that the software for your biosignal tracking is on Github. I've had a look, I can't find what I'm expecting, which is something to take measurements from your sensors then smooth and threshold them and reach a determination about whether the participant is asleep. Any pointers?

**Comment by tomasero** [comment]
Hello @marauder37, you're right! We only pushed the web app which is used to run experiments. I just uploaded the mobile app which allows for thresholding, recording of audio, and playing when the threshold is reached. Given the reliability of the sensors, we found no need in smoothing the signal. However, please feel free to explore and experiment as needed!

**Comment by marauder37** [comment]
Ace, thanks for the update!
