### ISSUE TITLE
Where to get the sensors?

### ISSUE THREAD

**Issue by quetzalsly** [tomasero/openSleep#4]
Sorry this is a beginner question but I am trying to figure out how one could build this. So the board itself can be orderered from an external company, but what about the sensors that go on the fingers and wrist and so on? How much would all of this cost and is it hard for a person without any previous hardware tinkering experience to build?

**Comment by tomasero** [comment]
Hello Roger,

Thank for your interest. You can take a look at the README.md on the GitHub repo. There you can find links to all the sensors you will need, and if you go to all the links and sum the prices you can figure out how much it will cost. There is no hardware design involve, just soldering a few components, so it should be manageable.

Best,
Tomás

**Comment by quetzalsly** [comment]
Thanks, a bit expensive for me right now but this is definitly something I want to make in the future because the whole project is fascinating to me :) Thanks for working on such things.
